name: Build Upstream Release

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: "The git ref to fetch from upstream and build"


jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repository
        uses: actions/checkout@v6
        with:
          repository: Kunzisoft/KeePassDX
          ref: ${{ github.event.inputs.ref }}
          path: src

      - name: Checkout custom patches (this repo)
        uses: actions/checkout@v6
        with:
          path: patches

      - name: Apply code patches
        working-directory: src
        run: |
          echo 'Applying code patches'
          git apply -3 ../patches/*.patch

      - name: Patch strings
        working-directory: src
        run: |
          echo 'Patching strings'
          chmod +x ../patches/patch_strings.sh && ../patches/patch_strings.sh

      - name: Pack it all up into an artifact for the next job
        uses: actions/upload-artifact@v7
        with:
          name: src.zip
          path: src

  build:
    runs-on: ubuntu-latest
    needs: prepare

    strategy:
      matrix:
        flavor:
          - free
          - libre

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grab the patched source code
        uses: actions/download-artifact@v8
        with:
          pattern: src.zip

      - name: Build Release ("${{ matrix.flavor }}" flavor)
        run: | 
          FLAVOR=$(echo '${{ matrix.flavor }}' | sed 's/.*/\u&/')
          chmod +x gradlew
          ./gradlew assemble${FLAVOR}Release -x lint -x lint${FLAVOR}Release

      - name: Save the APK
        uses: actions/upload-artifact@v7
        with:
          name: app-${{ matrix.flavor }}-release-unsigned.apk.zip
          path: app/build/outputs/apk/${{ matrix.flavor }}/release/app-${{ matrix.flavor }}-release-unsigned.apk

  sign:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        flavor:
          - free
          - libre

    steps:
      - name: Grab the unsigned APK
        uses: actions/download-artifact@v8
        with:
          pattern: app-${{ matrix.flavor }}-release-unsigned.apk.zip

      - name: Sign that shit
        id: sign
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: '34.0.0'
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.APK_SIGNING_KEYSTORE }}
          alias: ${{ secrets.APK_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.APK_SIGNING_KEYSTORE_PASSWORD }}

      - name: Save the signed APK
        uses: actions/upload-artifact@v7
        with:
          name: app-${{ matrix.flavor }}-release.apk.zip
          path: ${{ steps.sign.outputs.signedReleaseFile }}

  release:
    runs-on: ubuntu-latest
    needs: sign

    permissions:
      contents: write # for creating releases

    steps:
      - name: Grab the final (signed) binaries
        uses: actions/download-artifact@v8
        with:
          pattern: app-*-release.apk.zip

      - name: Rename - remove "-unsigned-signed"
        run: |
          tree
          for f in app-*-release.apk.zip/app-*-release-unsigned-signed.apk; do
            NAME="$(basename $f | sed 's/-unsigned-signed\.apk/.apk/')"
            mv $f $NAME
          done

      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.ref }}
          name: ${{ github.event.inputs.ref }}
          body: '[Upstream release](https://github.com/Kunzisoft/KeePassDX/releases/tag/${{ github.event.inputs.ref }})'
          draft: false
          prerelease: false
          files: app-*-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
